CREATE TABLE EVENTO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    DESCRICAO TEXT,
    DATA DATETIME,
    LOCAL VARCHAR(100),
    LOTE_ATUAL INT,
    VALOR_ATUAL DECIMAL,
    QUANTIDADE_MAX INT,
    QUANTIDADE_ATUAL INT
);

CREATE TABLE PESSOAS (
    ID VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(60),
    DATA_DE_NASCIMENTO DATE,
    ENDERECO_ID BIGINT
);

CREATE TABLE TRANSACAO_INGRESSO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PESSOA_ID BIGINT REFERENCES PESSOAS,
    EVENTO_ID BIGINT REFERENCES EVENTO,
    LOTE_COMPRADO INT,
    VALOR_PAGO DECIMAL,
    FORMA_DE_PAGAMENTO VARCHAR(20)
);

CREATE TABLE ENDERECO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LOGRADOURO VARCHAR(100),
    CEP VARCHAR(8),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(30),
    NUMERO INT,
    COMPLEMENTO VARCHAR(100)
);